import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import type { Icons } from 'ag-grid-community';
import type { LucideProps } from 'lucide-react';
import {
  AlertCircle,
  ArrowDown,
  ArrowDownFromLine,
  ArrowDownToLine,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  ArrowUpFromLine,
  ArrowUpToLine,
  Ban,
  BarChart3,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  ChevronsUpDown,
  Circle,
  CircleDot,
  ClipboardPaste,
  Columns3,
  Copy,
  Download,
  Droplet,
  Eye,
  EyeOff,
  FileSpreadsheet,
  Filter,
  GripHorizontal,
  GripVertical,
  LayoutGrid,
  Link2,
  ListFilter,
  ListFilterPlus,
  Loader2,
  Maximize2,
  Menu,
  Minimize2,
  MoreVertical,
  MoveVertical,
  Palette,
  Pencil,
  PieChart,
  Pin,
  PinOff,
  Plus,
  Rows3,
  Save,
  Scissors,
  Settings2,
  Sigma,
  SlidersHorizontal,
  Square,
  SquareCheck,
  SquareMinus,
  TableColumnsSplit,
  Trash2,
  Unlink2,
  Upload,
  UserRoundMinus,
  UserRoundPlus,
  X,
  XCircle,
} from 'lucide-react';

const base: LucideProps = {
  size: 14,
  strokeWidth: 2,
  absoluteStrokeWidth: true,
  'aria-hidden': true,
};

type IconComponent = React.ComponentType<LucideProps>;

function wrapSvg(markup: string, rtlMirror?: boolean): string {
  const style = rtlMirror ? ' style="display:inline-flex;transform:scaleX(-1)"' : '';
  return `<span class="ag-lucide-root" role="presentation"${style}>${markup}</span>`;
}

function L(Icon: IconComponent, extra?: Partial<LucideProps>, rtlMirror?: boolean): string {
  const el = <Icon {...base} {...extra} />;
  return wrapSvg(renderToStaticMarkup(el), rtlMirror);
}

function LSpin(Icon: IconComponent, extra?: Partial<LucideProps>): string {
  const el = <Icon {...base} {...extra} className="ag-lucide-spin-svg" />;
  return `<span class="ag-lucide-root ag-lucide-root--spin" role="presentation">${renderToStaticMarkup(el)}</span>`;
}

/**
 * Substitui os ícones internos do AG Grid por equivalentes Lucide (SVG via renderToStaticMarkup).
 */
export const agGridLucideIcons: Icons = {
  columnGroupOpened: L(ChevronDown),
  columnGroupClosed: L(ChevronRight),
  columnSelectClosed: L(Square),
  columnSelectOpen: L(SquareCheck),
  columnSelectIndeterminate: L(SquareMinus),
  accordionClosed: L(ChevronRight),
  accordionOpen: L(ChevronDown),
  accordionIndeterminate: L(SquareMinus),
  columnMovePin: L(Pin),
  columnMoveHide: L(EyeOff),
  columnMoveMove: L(MoveVertical),
  columnMoveLeft: L(ArrowLeft),
  columnMoveRight: L(ArrowRight),
  columnMoveGroup: L(Rows3),
  columnMoveValue: L(Sigma),
  columnMovePivot: L(LayoutGrid),
  dropNotAllowed: L(Ban),
  groupContracted: L(ChevronRight),
  groupExpanded: L(ChevronDown),
  setFilterGroupClosed: L(ChevronRight),
  setFilterGroupOpen: L(ChevronDown),
  setFilterGroupIndeterminate: L(SquareMinus),
  setFilterLoading: LSpin(Loader2),
  chart: L(BarChart3),
  close: L(X),
  cancel: L(XCircle),
  check: L(Check),
  first: L(ChevronsLeft),
  previous: L(ChevronLeft),
  next: L(ChevronRight),
  last: L(ChevronsRight),
  linked: L(Link2),
  unlinked: L(Unlink2),
  colorPicker: L(Palette),
  groupLoading: LSpin(Loader2),
  overlayLoading: LSpin(Loader2),
  overlayExporting: L(Upload),
  menu: L(Menu),
  legacyMenu: L(Menu),
  loadingMenuItems: LSpin(Loader2),
  menuAlt: L(MoreVertical),
  filter: L(Filter),
  filterActive: L(ListFilter),
  filterAdd: L(ListFilterPlus),
  filterCardExpand: L(ChevronsDown),
  filterCardCollapse: L(ChevronsUp),
  filterCardEditing: L(Pencil),
  filterTab: L(ListFilter),
  filtersToolPanel: L(Filter),
  columns: L(TableColumnsSplit),
  columnsToolPanel: L(Columns3),
  maximize: L(Maximize2),
  minimize: L(Minimize2),
  menuPin: L(Pin),
  menuValue: L(Sigma),
  menuAddRowGroup: L(UserRoundPlus),
  menuRemoveRowGroup: L(UserRoundMinus),
  clipboardCopy: L(Copy),
  clipboardCut: L(Scissors),
  clipboardPaste: L(ClipboardPaste),
  pivotPanel: L(LayoutGrid),
  rowGroupPanel: L(Rows3),
  valuePanel: L(Sigma),
  columnDrag: L(GripVertical),
  rowDrag: L(GripHorizontal),
  rowPin: L(Pin),
  rowPinTop: L(ArrowUpToLine),
  rowPinBottom: L(ArrowDownToLine),
  rowUnpin: L(PinOff),
  save: L(Save),
  csvExport: L(FileSpreadsheet),
  excelExport: L(FileSpreadsheet),
  smallDown: L(ChevronDown),
  selectOpen: L(ChevronDown),
  richSelectOpen: L(ChevronsUpDown),
  richSelectRemove: L(X),
  richSelectLoading: LSpin(Loader2),
  smallLeft: L(ChevronLeft),
  smallRight: L(ChevronRight),
  panelDelimiter: L(GripVertical),
  panelDelimiterRtl: L(GripVertical, undefined, true),
  subMenuOpen: L(ChevronRight),
  subMenuOpenRtl: L(ChevronLeft),
  smallUp: L(ChevronUp),
  sortAscending: L(ArrowUp),
  sortDescending: L(ArrowDown),
  sortAbsoluteAscending: L(ArrowUpFromLine),
  sortAbsoluteDescending: L(ArrowDownFromLine),
  sortUnSort: L(ArrowUpDown),
  advancedFilterBuilder: L(SlidersHorizontal),
  advancedFilterBuilderDrag: L(GripVertical),
  advancedFilterBuilderInvalid: L(AlertCircle),
  advancedFilterBuilderMoveUp: L(ArrowUp),
  advancedFilterBuilderMoveDown: L(ArrowDown),
  advancedFilterBuilderAdd: L(Plus),
  advancedFilterBuilderRemove: L(Trash2),
  advancedFilterBuilderSelectOpen: L(ChevronDown),
  chartsMenu: L(PieChart),
  chartsMenuEdit: L(Pencil),
  chartsMenuAdvancedSettings: L(Settings2),
  chartsMenuAdd: L(Plus),
  chartsColorPicker: L(Droplet),
  chartsThemePrevious: L(ChevronLeft),
  chartsThemeNext: L(ChevronRight),
  chartsDownload: L(Download),
  ensureColumnVisible: L(Eye),
  checkboxChecked: L(SquareCheck),
  checkboxIndeterminate: L(SquareMinus),
  checkboxUnchecked: L(Square),
  radioButtonOn: L(CircleDot),
  radioButtonOff: L(Circle),
};
